Reshel pkexec Exploit Environment Variable Artifact:
  query: SELECT p.pid, p.name, e.pid, e.key, e.value from processes p JOIN process_envs
    e ON p.pid=e.pid WHERE p.name LIKE '%pkexec' AND p.pid=e.pid AND e.key='GCONV_PATH'
    AND e.value LIKE './%';
  interval: 86400
  snapshot: true
  description: "Reshel is a Unix based trojan with the backdoor capability that creates a TCP
    bind shell on the victim's machine, leading the attacker to connect to the victim's machine
    with the elevated privileges while gaining access to the shell to run any arbitrary commands
    or shellcode. The pkexec utility allows an authorized user to execute the program as
    another user, according to the polkit policy definitions using the setuid feature. This
    vulnerable version doesn't handle the calling  parameters count correctly, resulting in active
    environment variables executing commands."
  references:
  - ef130f1941077ffe383fe90e241620dde771cd0dd496dad29d2048d5fc478faf
  - 8a9dcc7767a7c17f77d4cecdbe28b2e71d85f5d84b04dcb9f7b815b1fec1f0cb
  - 0f0663fc26b18212485149e3e22c3dd4b8900ea8dca7c084dbe09fef02cfdade
  - bba3d979a869cf7b403bd01f3660e4953576375f2122fdcb32d6a03cd9de48f8
  - cac09cdcbd904068bd27ff784a5bf8f7b2165c0da5063047f1f49075dd2e34c3
  - 921a3c6ba47c4801477c7ac7402671d34613a4b6ab4b9e4077c3f6b7969c26da
  - 30c5b52c62984a2592a6982bd39b9b94bd758565084d79397487efe60664506c
  - 36b5edd93920b197ff63e452acfa728d85e70c25b21b16872b8896f6c2016610
  - 3adc2d9d0f8c78f13845eb832563dbe4e7e0a51d9e0011a7ea6ab49f351a3e83
  - 5e9755ab62f82d44c4872be2d59457f47640b3a1d2dcd9393f55ada2d5b7107b
  - ae9f370c89f0191492ed9c17a224d9c41778b47ca2768f732b4de6ee7d0d1459
  mitre_tactics:
  - privilege-escalation: TA0004
  mitre_techniques:
  - exploitation-for-privilege-escalation: T1068
  platform:
  - linux
  - osx
